"""empty message

Revision ID: 54e57a59e6d5
Revises: 18aa439633a8
Create Date: 2023-04-27 15:26:54.171750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e57a59e6d5'
down_revision = '18aa439633a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birds', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('birds', 'image')
    # ### end Alembic commands ###
